import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext(null)
export const useLanguage = () => useContext(LanguageContext)

export const APP_LANGUAGES = [
  'English', 'Tamil', 'Hindi', 'Telugu', 'Malayalam', 'Kannada'
]

export const APP_LABELS = {
  English: {
    // Sidebar
    dashboard: 'Dashboard', generate: 'Generate', history: 'History',
    pricing: 'Pricing', helpdesk: 'Help Desk', profile: 'Profile',
    settings: 'Settings', signout: 'Sign out', studio: 'Creative Studio',
    // Dashboard
    welcomeBack: 'Welcome back', readyToCreate: 'Ready to create something amazing today?',
    totalCreated: 'Total Created', scripts: 'Scripts', jingles: 'Jingles', campaigns: 'Campaigns',
    quickCreate: 'Quick Create', recentGenerations: 'Recent Generations', viewAll: 'View all →',
    noGenerations: 'No generations yet.', createFirst: 'Create your first →',
    script: 'Script', visual: 'Visual', music: 'Music', campaign: 'Campaign',
    // History
    generationHistory: 'Generation', historyItalic: 'History',
    generationsSession: 'generations this session', clearAll: 'Clear All',
    noHistory: 'No history yet. Generate some content first!',
    copy: 'Copy', copied: '✓ Copied', download: 'Download .txt',
    // Pricing
    simplePricing: 'Simple', pricingItalic: 'Pricing',
    noSurprises: 'No surprises. Cancel anytime.',
    mostPopular: 'Most Popular', getStarted: 'Get Started',
    startTrial: 'Start Free Trial', contactSales: 'Contact Sales',
    // Profile
    yourProfile: 'Your', profileTitle: 'Profile',
    freePlan: 'Free Plan', googleAccount: 'Google Account',
    editName: '✏️ Edit Display Name', currentName: 'Current Name',
    edit: 'Edit', save: 'Save Name', cancel: 'Cancel', saving: 'Saving...',
    emailAddress: '📧 Email Address', currentEmail: 'Current Email',
    change: 'Change', updateEmail: 'Update Email', updatingEmail: 'Saving...',
    newEmailLabel: 'New Email Address', currentPassLabel: 'Current Password (required)',
    passwordSecurity: '🔒 Password & Security',
    changePassword: '🔑 Change Password', sendResetEmail: '📧 Send Reset Email',
    currentPass: 'Current Password', newPass: 'New Password (min 6 characters)',
    confirmPass: 'Confirm New Password', updatePassword: 'Update Password', updating: 'Updating...',
    accountInfo: 'ℹ️ Account Info',
    displayName: 'Display Name', email: 'Email', userId: 'User ID',
    signinMethod: 'Sign-in Method', accountCreated: 'Account Created',
    dangerZone: '⚠️ Danger Zone', deleteAccount: 'Delete Account',
    deleteDesc: 'Permanently delete your account and all data.',
    delete: 'Delete', confirmDelete: 'Yes, Delete My Account',
    deleteWarning: '⚠️ Are you sure? This action cannot be undone. All your data will be permanently deleted.',
    googleEmailNote: '🔗 Your account is linked to Google. Email is managed by Google and cannot be changed here.',
    googlePassNote: '🔗 You signed in with Google. Password is managed by Google.',
    google: 'Google', emailPassword: 'Email & Password', unknown: 'Unknown', notSet: 'Not set',
    tooShort: 'Too short', fair: 'Fair', good: 'Good', strong: 'Strong',
    // Generate
    generateTitle: 'Generate', generateItalic: 'Creative Content',
    generateDesc: 'Fill in the details and let AI do the rest. 🎤 Click mic icons to use voice input.',
    brandDetails: '✦ Brand Details', brandName: 'Brand Name *', industry: 'Industry',
    targetAudience: 'Target Audience', tone: 'Tone', themeMsg: 'Theme / Key Message *',
    outputLang: 'Output Language', cultureProfile: '🇮🇳 Culture Profile',
    region: 'Region', festival: 'Festival / Occasion',
    culturalElements: 'Cultural Elements (pick 2–5)', elementsSelected: 'element(s) selected',
    generating: 'Generating', generatingDesc: 'Crafting your content with Indian cultural context...',
    generatingTime: 'This may take 10–20 seconds',
    generatedOutput: '✦ Generated Output',
    // Settings
    settingsTitle: 'Settings',
  },
  Tamil: {
    dashboard: 'டாஷ்போர்டு', generate: 'உருவாக்கு', history: 'வரலாறு',
    pricing: 'விலை', helpdesk: 'உதவி மேசை', profile: 'சுயவிவரம்',
    settings: 'அமைப்புகள்', signout: 'வெளியேறு', studio: 'படைப்பு ஸ்டுடியோ',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்', readyToCreate: 'இன்று ஏதாவது அற்புதமானதை உருவாக்க தயாரா?',
    totalCreated: 'மொத்தம் உருவாக்கியது', scripts: 'திரைக்கதைகள்', jingles: 'ஜிங்கிள்கள்', campaigns: 'பிரச்சாரங்கள்',
    quickCreate: 'விரைவு உருவாக்கம்', recentGenerations: 'சமீபத்திய உருவாக்கங்கள்', viewAll: 'அனைத்தும் காண →',
    noGenerations: 'இன்னும் உருவாக்கங்கள் இல்லை.', createFirst: 'முதலில் உருவாக்கு →',
    script: 'திரைக்கதை', visual: 'காட்சி', music: 'இசை', campaign: 'பிரச்சாரம்',
    generationHistory: 'உருவாக்கல்', historyItalic: 'வரலாறு',
    generationsSession: 'இந்த அமர்வில் உருவாக்கங்கள்', clearAll: 'அனைத்தும் அழி',
    noHistory: 'வரலாறு இல்லை. முதலில் உள்ளடக்கத்தை உருவாக்கவும்!',
    copy: 'நகல்', copied: '✓ நகலெடுக்கப்பட்டது', download: 'பதிவிறக்கம் .txt',
    simplePricing: 'எளிய', pricingItalic: 'விலை',
    noSurprises: 'எந்த ஆச்சரியமும் இல்லை. எப்போது வேண்டுமானாலும் ரத்து செய்யலாம்.',
    mostPopular: 'மிகவும் பிரபலம்', getStarted: 'தொடங்கு', startTrial: 'இலவச சோதனை தொடங்கு', contactSales: 'விற்பனையை தொடர்பு கொள்',
    yourProfile: 'உங்கள்', profileTitle: 'சுயவிவரம்',
    freePlan: 'இலவச திட்டம்', googleAccount: 'Google கணக்கு',
    editName: '✏️ பெயர் திருத்து', currentName: 'தற்போதைய பெயர்',
    edit: 'திருத்து', save: 'பெயர் சேமி', cancel: 'ரத்து', saving: 'சேமிக்கிறது...',
    emailAddress: '📧 மின்னஞ்சல்', currentEmail: 'தற்போதைய மின்னஞ்சல்',
    change: 'மாற்று', updateEmail: 'மின்னஞ்சல் புதுப்பி', updatingEmail: 'சேமிக்கிறது...',
    newEmailLabel: 'புதிய மின்னஞ்சல்', currentPassLabel: 'தற்போதைய கடவுச்சொல்',
    passwordSecurity: '🔒 கடவுச்சொல் & பாதுகாப்பு',
    changePassword: '🔑 கடவுச்சொல் மாற்று', sendResetEmail: '📧 மீட்டமைப்பு மின்னஞ்சல்',
    currentPass: 'தற்போதைய கடவுச்சொல்', newPass: 'புதிய கடவுச்சொல் (குறைந்தது 6)',
    confirmPass: 'கடவுச்சொல் உறுதிப்படுத்து', updatePassword: 'கடவுச்சொல் புதுப்பி', updating: 'புதுப்பிக்கிறது...',
    accountInfo: 'ℹ️ கணக்கு தகவல்',
    displayName: 'காட்சிப் பெயர்', email: 'மின்னஞ்சல்', userId: 'பயனர் ID',
    signinMethod: 'உள்நுழைவு முறை', accountCreated: 'கணக்கு உருவாக்கப்பட்டது',
    dangerZone: '⚠️ ஆபத்தான பகுதி', deleteAccount: 'கணக்கை நீக்கு',
    deleteDesc: 'உங்கள் கணக்கையும் அனைத்து தரவையும் நிரந்தரமாக நீக்கவும்.',
    delete: 'நீக்கு', confirmDelete: 'ஆம், என் கணக்கை நீக்கு',
    deleteWarning: '⚠️ நீங்கள் உறுதியாக இருக்கிறீர்களா? இந்த செயலை மீட்டெடுக்க முடியாது.',
    googleEmailNote: '🔗 உங்கள் கணக்கு Google உடன் இணைக்கப்பட்டுள்ளது.',
    googlePassNote: '🔗 நீங்கள் Google மூலம் உள்நுழைந்தீர்கள்.',
    google: 'Google', emailPassword: 'மின்னஞ்சல் & கடவுச்சொல்', unknown: 'தெரியாது', notSet: 'அமைக்கப்படவில்லை',
    tooShort: 'மிகவும் குறுகியது', fair: 'சாதாரண', good: 'நல்லது', strong: 'வலுவான',
    generateTitle: 'உருவாக்கு', generateItalic: 'படைப்பு உள்ளடக்கம்',
    generateDesc: 'விவரங்களை நிரப்பி AI ஐ செய்யட்டும். 🎤 குரல் உள்ளீட்டிற்கு மைக் கிளிக் செய்யவும்.',
    brandDetails: '✦ பிராண்ட் விவரங்கள்', brandName: 'பிராண்ட் பெயர் *', industry: 'தொழில்துறை',
    targetAudience: 'இலக்கு பார்வையாளர்கள்', tone: 'தொனி', themeMsg: 'தீம் / முக்கிய செய்தி *',
    outputLang: 'வெளியீட்டு மொழி', cultureProfile: '🇮🇳 கலாச்சார சுயவிவரம்',
    region: 'பிராந்தியம்', festival: 'திருவிழா / நிகழ்வு',
    culturalElements: 'கலாச்சார கூறுகள் (2-5 தேர்ந்தெடு)', elementsSelected: 'கூறு(கள்) தேர்ந்தெடுக்கப்பட்டன',
    generating: 'உருவாக்குகிறது', generatingDesc: 'இந்திய கலாச்சார சூழலில் உருவாக்குகிறது...',
    generatingTime: 'இது 10-20 வினாடிகள் ஆகலாம்',
    generatedOutput: '✦ உருவாக்கப்பட்ட வெளியீடு',
    settingsTitle: 'அமைப்புகள்',
  },
  Hindi: {
    dashboard: 'डैशबोर्ड', generate: 'बनाएं', history: 'इतिहास',
    pricing: 'मूल्य', helpdesk: 'हेल्प डेस्क', profile: 'प्रोफ़ाइल',
    settings: 'सेटिंग्स', signout: 'साइन आउट', studio: 'क्रिएटिव स्टूडियो',
    welcomeBack: 'वापस स्वागत है', readyToCreate: 'आज कुछ अद्भुत बनाने के लिए तैयार हैं?',
    totalCreated: 'कुल बनाया', scripts: 'स्क्रिप्ट', jingles: 'जिंगल्स', campaigns: 'अभियान',
    quickCreate: 'त्वरित बनाएं', recentGenerations: 'हाल की पीढ़ियाँ', viewAll: 'सब देखें →',
    noGenerations: 'अभी तक कोई पीढ़ी नहीं।', createFirst: 'पहला बनाएं →',
    script: 'स्क्रिप्ट', visual: 'विज़ुअल', music: 'संगीत', campaign: 'अभियान',
    generationHistory: 'जनरेशन', historyItalic: 'इतिहास',
    generationsSession: 'इस सत्र में पीढ़ियाँ', clearAll: 'सब हटाएं',
    noHistory: 'कोई इतिहास नहीं। पहले कुछ सामग्री बनाएं!',
    copy: 'कॉपी', copied: '✓ कॉपी हो गया', download: 'डाउनलोड .txt',
    simplePricing: 'सरल', pricingItalic: 'मूल्य निर्धारण',
    noSurprises: 'कोई आश्चर्य नहीं। कभी भी रद्द करें।',
    mostPopular: 'सबसे लोकप्रिय', getStarted: 'शुरू करें', startTrial: 'फ्री ट्रायल शुरू करें', contactSales: 'बिक्री से संपर्क करें',
    yourProfile: 'आपका', profileTitle: 'प्रोफ़ाइल',
    freePlan: 'मुफ्त योजना', googleAccount: 'Google खाता',
    editName: '✏️ नाम संपादित करें', currentName: 'वर्तमान नाम',
    edit: 'संपादित करें', save: 'नाम सहेजें', cancel: 'रद्द करें', saving: 'सहेज रहा है...',
    emailAddress: '📧 ईमेल पता', currentEmail: 'वर्तमान ईमेल',
    change: 'बदलें', updateEmail: 'ईमेल अपडेट करें', updatingEmail: 'सहेज रहा है...',
    newEmailLabel: 'नया ईमेल पता', currentPassLabel: 'वर्तमान पासवर्ड (आवश्यक)',
    passwordSecurity: '🔒 पासवर्ड और सुरक्षा',
    changePassword: '🔑 पासवर्ड बदलें', sendResetEmail: '📧 रीसेट ईमेल भेजें',
    currentPass: 'वर्तमान पासवर्ड', newPass: 'नया पासवर्ड (न्यूनतम 6)',
    confirmPass: 'पासवर्ड की पुष्टि करें', updatePassword: 'पासवर्ड अपडेट करें', updating: 'अपडेट हो रहा है...',
    accountInfo: 'ℹ️ खाता जानकारी',
    displayName: 'प्रदर्शन नाम', email: 'ईमेल', userId: 'उपयोगकर्ता ID',
    signinMethod: 'साइन-इन विधि', accountCreated: 'खाता बनाया गया',
    dangerZone: '⚠️ खतरनाक क्षेत्र', deleteAccount: 'खाता हटाएं',
    deleteDesc: 'अपना खाता और सारा डेटा स्थायी रूप से हटाएं।',
    delete: 'हटाएं', confirmDelete: 'हाँ, मेरा खाता हटाएं',
    deleteWarning: '⚠️ क्या आप सुनिश्चित हैं? यह क्रिया पूर्ववत नहीं की जा सकती।',
    googleEmailNote: '🔗 आपका खाता Google से जुड़ा है।',
    googlePassNote: '🔗 आपने Google से साइन इन किया।',
    google: 'Google', emailPassword: 'ईमेल और पासवर्ड', unknown: 'अज्ञात', notSet: 'सेट नहीं',
    tooShort: 'बहुत छोटा', fair: 'ठीक है', good: 'अच्छा', strong: 'मजबूत',
    generateTitle: 'बनाएं', generateItalic: 'क्रिएटिव कंटेंट',
    generateDesc: 'विवरण भरें और AI को बाकी काम करने दें। 🎤 वॉयस इनपुट के लिए माइक क्लिक करें।',
    brandDetails: '✦ ब्रांड विवरण', brandName: 'ब्रांड नाम *', industry: 'उद्योग',
    targetAudience: 'लक्षित दर्शक', tone: 'टोन', themeMsg: 'थीम / मुख्य संदेश *',
    outputLang: 'आउटपुट भाषा', cultureProfile: '🇮🇳 संस्कृति प्रोफ़ाइल',
    region: 'क्षेत्र', festival: 'त्योहार / अवसर',
    culturalElements: 'सांस्कृतिक तत्व (2-5 चुनें)', elementsSelected: 'तत्व चुने गए',
    generating: 'बना रहा है', generatingDesc: 'भारतीय सांस्कृतिक संदर्भ के साथ बना रहा है...',
    generatingTime: 'इसमें 10-20 सेकंड लग सकते हैं',
    generatedOutput: '✦ उत्पन्न आउटपुट',
    settingsTitle: 'सेटिंग्स',
  },
  Telugu: {
    dashboard: 'డాష్‌బోర్డ్', generate: 'సృష్టించు', history: 'చరిత్ర',
    pricing: 'ధర', helpdesk: 'హెల్ప్ డెస్క్', profile: 'ప్రొఫైల్',
    settings: 'సెట్టింగ్స్', signout: 'సైన్ అవుట్', studio: 'క్రియేటివ్ స్టూడియో',
    welcomeBack: 'తిరిగి స్వాగతం', readyToCreate: 'ఈరోజు అద్భుతమైనది సృష్టించడానికి సిద్ధంగా ఉన్నారా?',
    totalCreated: 'మొత్తం సృష్టించారు', scripts: 'స్క్రిప్ట్‌లు', jingles: 'జింగిల్స్', campaigns: 'క్యాంపెయిన్లు',
    quickCreate: 'త్వరిత సృష్టి', recentGenerations: 'ఇటీవలి జనరేషన్లు', viewAll: 'అన్నీ చూడండి →',
    noGenerations: 'ఇంకా జనరేషన్లు లేవు.', createFirst: 'మొదటిది సృష్టించండి →',
    script: 'స్క్రిప్ట్', visual: 'విజువల్', music: 'సంగీతం', campaign: 'క్యాంపెయిన్',
    generationHistory: 'జనరేషన్', historyItalic: 'చరిత్ర',
    generationsSession: 'ఈ సెషన్‌లో జనరేషన్లు', clearAll: 'అన్నీ తొలగించు',
    noHistory: 'చరిత్ర లేదు. ముందు కంటెంట్ సృష్టించండి!',
    copy: 'కాపీ', copied: '✓ కాపీ అయింది', download: 'డౌన్‌లోడ్ .txt',
    simplePricing: 'సరళమైన', pricingItalic: 'ధర నిర్ణయం',
    noSurprises: 'ఆశ్చర్యాలు లేవు. ఎప్పుడైనా రద్దు చేయండి.',
    mostPopular: 'అత్యంత ప్రజాదరణ', getStarted: 'ప్రారంభించండి', startTrial: 'ఉచిత ట్రయల్ ప్రారంభించండి', contactSales: 'విక్రయాలను సంప్రదించండి',
    yourProfile: 'మీ', profileTitle: 'ప్రొఫైల్',
    freePlan: 'ఉచిత ప్లాన్', googleAccount: 'Google ఖాతా',
    editName: '✏️ పేరు సవరించు', currentName: 'ప్రస్తుత పేరు',
    edit: 'సవరించు', save: 'పేరు సేవ్ చేయి', cancel: 'రద్దు', saving: 'సేవ్ అవుతోంది...',
    emailAddress: '📧 ఇమెయిల్ చిరునామా', currentEmail: 'ప్రస్తుత ఇమెయిల్',
    change: 'మార్చు', updateEmail: 'ఇమెయిల్ నవీకరించు', updatingEmail: 'సేవ్ అవుతోంది...',
    newEmailLabel: 'కొత్త ఇమెయిల్', currentPassLabel: 'ప్రస్తుత పాస్‌వర్డ్',
    passwordSecurity: '🔒 పాస్‌వర్డ్ & భద్రత',
    changePassword: '🔑 పాస్‌వర్డ్ మార్చు', sendResetEmail: '📧 రీసెట్ ఇమెయిల్ పంపు',
    currentPass: 'ప్రస్తుత పాస్‌వర్డ్', newPass: 'కొత్త పాస్‌వర్డ్ (కనీసం 6)',
    confirmPass: 'పాస్‌వర్డ్ నిర్ధారించు', updatePassword: 'పాస్‌వర్డ్ నవీకరించు', updating: 'నవీకరిస్తోంది...',
    accountInfo: 'ℹ️ ఖాతా సమాచారం',
    displayName: 'డిస్‌ప్లే పేరు', email: 'ఇమెయిల్', userId: 'యూజర్ ID',
    signinMethod: 'సైన్-ఇన్ పద్ధతి', accountCreated: 'ఖాతా సృష్టించబడింది',
    dangerZone: '⚠️ ప్రమాద జోన్', deleteAccount: 'ఖాతా తొలగించు',
    deleteDesc: 'మీ ఖాతాను మరియు అన్ని డేటాను శాశ్వతంగా తొలగించండి.',
    delete: 'తొలగించు', confirmDelete: 'అవును, నా ఖాతా తొలగించు',
    deleteWarning: '⚠️ మీరు ఖచ్చితంగా ఉన్నారా? ఈ చర్యను రద్దు చేయలేరు.',
    googleEmailNote: '🔗 మీ ఖాతా Google తో లింక్ చేయబడింది.',
    googlePassNote: '🔗 మీరు Google తో సైన్ ఇన్ చేశారు.',
    google: 'Google', emailPassword: 'ఇమెయిల్ & పాస్‌వర్డ్', unknown: 'తెలియదు', notSet: 'సెట్ కాలేదు',
    tooShort: 'చాలా చిన్నది', fair: 'సరైనది', good: 'మంచిది', strong: 'బలమైనది',
    generateTitle: 'సృష్టించు', generateItalic: 'క్రియేటివ్ కంటెంట్',
    generateDesc: 'వివరాలు నింపండి మరియు AI మిగతాది చేయనివ్వండి.',
    brandDetails: '✦ బ్రాండ్ వివరాలు', brandName: 'బ్రాండ్ పేరు *', industry: 'పరిశ్రమ',
    targetAudience: 'లక్ష్య ప్రేక్షకులు', tone: 'టోన్', themeMsg: 'థీమ్ / కీ మెసేజ్ *',
    outputLang: 'అవుట్‌పుట్ భాష', cultureProfile: '🇮🇳 సంస్కృతి ప్రొఫైల్',
    region: 'ప్రాంతం', festival: 'పండుగ / సందర్భం',
    culturalElements: 'సాంస్కృతిక అంశాలు (2-5 ఎంచుకోండి)', elementsSelected: 'అంశ(లు) ఎంచుకోబడ్డాయి',
    generating: 'సృష్టిస్తోంది', generatingDesc: 'భారతీయ సాంస్కృతిక సందర్భంతో సృష్టిస్తోంది...',
    generatingTime: 'ఇది 10-20 సెకన్లు పట్టవచ్చు',
    generatedOutput: '✦ సృష్టించిన అవుట్‌పుట్',
    settingsTitle: 'సెట్టింగ్స్',
  },
  Malayalam: {
    dashboard: 'ഡാഷ്‌ബോർഡ്', generate: 'സൃഷ്ടിക്കുക', history: 'ചരിത്രം',
    pricing: 'വില', helpdesk: 'ഹെൽപ്പ് ഡെസ്ക്', profile: 'പ്രൊഫൈൽ',
    settings: 'ക്രമീകരണങ്ങൾ', signout: 'സൈൻ ഔട്ട്', studio: 'ക്രിയേറ്റീവ് സ്റ്റുഡിയോ',
    welcomeBack: 'തിരിച്ചു സ്വാഗതം', readyToCreate: 'ഇന്ന് എന്തെങ്കിലും അദ്ഭുതകരമായത് സൃഷ്ടിക്കാൻ തയ്യാറാണോ?',
    totalCreated: 'ആകെ സൃഷ്ടിച്ചത്', scripts: 'സ്ക്രിപ്റ്റുകൾ', jingles: 'ജിംഗിൾസ്', campaigns: 'കാമ്പെയ്നുകൾ',
    quickCreate: 'ദ്രുത സൃഷ്ടി', recentGenerations: 'സമീപകാല ജനറേഷനുകൾ', viewAll: 'എല്ലാം കാണുക →',
    noGenerations: 'ഇതുവരെ ജനറേഷനുകൾ ഇല്ല.', createFirst: 'ആദ്യത്തേത് സൃഷ്ടിക്കുക →',
    script: 'സ്ക്രിപ്റ്റ്', visual: 'വിഷ്വൽ', music: 'സംഗീതം', campaign: 'കാമ്പെയ്ൻ',
    generationHistory: 'ജനറേഷൻ', historyItalic: 'ചരിത്രം',
    generationsSession: 'ഈ സെഷനിൽ ജനറേഷനുകൾ', clearAll: 'എല്ലാം മായ്ക്കുക',
    noHistory: 'ചരിത്രമില്ല. ആദ്യം ഉള്ളടക്കം സൃഷ്ടിക്കുക!',
    copy: 'പകർത്തുക', copied: '✓ പകർത്തി', download: 'ഡൗൺലോഡ് .txt',
    simplePricing: 'ലളിതമായ', pricingItalic: 'വില നിർണ്ണയം',
    noSurprises: 'ആശ്ചര്യങ്ങൾ ഇല്ല. എപ്പോൾ വേണമെങ്കിലും റദ്ദാക്കുക.',
    mostPopular: 'ഏറ്റവും ജനപ്രിയം', getStarted: 'ആരംഭിക്കുക', startTrial: 'സൗജന്യ ട്രയൽ ആരംഭിക്കുക', contactSales: 'വിൽപ്പന ബന്ധപ്പെടുക',
    yourProfile: 'നിങ്ങളുടെ', profileTitle: 'പ്രൊഫൈൽ',
    freePlan: 'സൗജന്യ പ്ലാൻ', googleAccount: 'Google അക്കൗണ്ട്',
    editName: '✏️ പേര് തിരുത്തുക', currentName: 'നിലവിലെ പേര്',
    edit: 'തിരുത്തുക', save: 'പേര് സേവ് ചെയ്യുക', cancel: 'റദ്ദാക്കുക', saving: 'സേവ് ചെയ്യുന്നു...',
    emailAddress: '📧 ഇമെയിൽ വിലാസം', currentEmail: 'നിലവിലെ ഇമെയിൽ',
    change: 'മാറ്റുക', updateEmail: 'ഇമെയിൽ അപ്ഡേറ്റ് ചെയ്യുക', updatingEmail: 'സേവ് ചെയ്യുന്നു...',
    newEmailLabel: 'പുതിയ ഇമെയിൽ', currentPassLabel: 'നിലവിലെ പാസ്‌വേഡ്',
    passwordSecurity: '🔒 പാസ്‌വേഡ് & സുരക്ഷ',
    changePassword: '🔑 പാസ്‌വേഡ് മാറ്റുക', sendResetEmail: '📧 റീസെറ്റ് ഇമെയിൽ അയക്കുക',
    currentPass: 'നിലവിലെ പാസ്‌വേഡ്', newPass: 'പുതിയ പാസ്‌വേഡ് (കുറഞ്ഞത് 6)',
    confirmPass: 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക', updatePassword: 'പാസ്‌വേഡ് അപ്ഡേറ്റ് ചെയ്യുക', updating: 'അപ്ഡേറ്റ് ചെയ്യുന്നു...',
    accountInfo: 'ℹ️ അക്കൗണ്ട് വിവരം',
    displayName: 'ഡിസ്‌പ്ലേ നാമം', email: 'ഇമെയിൽ', userId: 'യൂസർ ID',
    signinMethod: 'സൈൻ-ഇൻ രീതി', accountCreated: 'അക്കൗണ്ട് സൃഷ്ടിച്ചു',
    dangerZone: '⚠️ അപകട മേഖല', deleteAccount: 'അക്കൗണ്ട് ഇല്ലാതാക്കുക',
    deleteDesc: 'നിങ്ങളുടെ അക്കൗണ്ടും എല്ലാ ഡേറ്റയും ശാശ്വതമായി ഇല്ലാതാക്കുക.',
    delete: 'ഇല്ലാതാക്കുക', confirmDelete: 'അതെ, എന്റെ അക്കൗണ്ട് ഇല്ലാതാക്കുക',
    deleteWarning: '⚠️ നിങ്ങൾ ഉറപ്പാണോ? ഈ പ്രവർത്തനം പഴയ നിലയിലേക്ക് മടക്കാനാവില്ല.',
    googleEmailNote: '🔗 നിങ്ങളുടെ അക്കൗണ്ട് Google-മായി ലിങ്ക് ചെയ്തിരിക്കുന്നു.',
    googlePassNote: '🔗 നിങ്ങൾ Google ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്തു.',
    google: 'Google', emailPassword: 'ഇമെയിൽ & പാസ്‌വേഡ്', unknown: 'അജ്ഞാതം', notSet: 'സെറ്റ് ചെയ്തിട്ടില്ല',
    tooShort: 'വളരെ ചെറുത്', fair: 'ഓക്കെ', good: 'നല്ലത്', strong: 'ശക്തമായ',
    generateTitle: 'സൃഷ്ടിക്കുക', generateItalic: 'ക്രിയേറ്റീവ് കണ്ടെന്റ്',
    generateDesc: 'വിവരങ്ങൾ പൂരിപ്പിക്കുക, AI ബാക്കി ചെയ്യട്ടെ.',
    brandDetails: '✦ ബ്രാൻഡ് വിവരങ്ങൾ', brandName: 'ബ്രാൻഡ് നാമം *', industry: 'വ്യവസായം',
    targetAudience: 'ലക്ഷ്യ പ്രേക്ഷകർ', tone: 'ടോൺ', themeMsg: 'തീം / പ്രധാന സന്ദേശം *',
    outputLang: 'ഔട്ട്പുട്ട് ഭാഷ', cultureProfile: '🇮🇳 സംസ്കാര പ്രൊഫൈൽ',
    region: 'പ്രദേശം', festival: 'ഉത്സവം / അവസരം',
    culturalElements: 'സാംസ്കാരിക ഘടകങ്ങൾ (2-5 തിരഞ്ഞെടുക്കുക)', elementsSelected: 'ഘടക(ങ്ങൾ) തിരഞ്ഞെടുത്തു',
    generating: 'സൃഷ്ടിക്കുന്നു', generatingDesc: 'ഇന്ത്യൻ സാംസ്കാരിക സന്ദർഭത്തിൽ സൃഷ്ടിക്കുന്നു...',
    generatingTime: 'ഇത് 10-20 സെക്കൻഡ് എടുക്കാം',
    generatedOutput: '✦ സൃഷ്ടിച്ച ഔട്ട്പുട്ട്',
    settingsTitle: 'ക്രമീകരണങ്ങൾ',
  },
  Kannada: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', generate: 'ರಚಿಸಿ', history: 'ಇತಿಹಾಸ',
    pricing: 'ಬೆಲೆ', helpdesk: 'ಸಹಾಯ ಮೇಜು', profile: 'ಪ್ರೊಫೈಲ್',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು', signout: 'ಸೈನ್ ಔಟ್', studio: 'ಕ್ರಿಯೇಟಿವ್ ಸ್ಟುಡಿಯೋ',
    welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ', readyToCreate: 'ಇಂದು ಏನಾದರೂ ಅದ್ಭುತವನ್ನು ರಚಿಸಲು ತಯಾರಾಗಿದ್ದೀರಾ?',
    totalCreated: 'ಒಟ್ಟು ರಚಿಸಲಾಗಿದೆ', scripts: 'ಸ್ಕ್ರಿಪ್ಟ್‌ಗಳು', jingles: 'ಜಿಂಗಲ್ಸ್', campaigns: 'ಪ್ರಚಾರಗಳು',
    quickCreate: 'ತ್ವರಿತ ರಚನೆ', recentGenerations: 'ಇತ್ತೀಚಿನ ಜನರೇಷನ್‌ಗಳು', viewAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ →',
    noGenerations: 'ಇನ್ನೂ ಜನರೇಷನ್‌ಗಳಿಲ್ಲ.', createFirst: 'ಮೊದಲನೆಯದನ್ನು ರಚಿಸಿ →',
    script: 'ಸ್ಕ್ರಿಪ್ಟ್', visual: 'ವಿಷುಯಲ್', music: 'ಸಂಗೀತ', campaign: 'ಪ್ರಚಾರ',
    generationHistory: 'ಜನರೇಷನ್', historyItalic: 'ಇತಿಹಾಸ',
    generationsSession: 'ಈ ಸೆಷನ್‌ನಲ್ಲಿ ಜನರೇಷನ್‌ಗಳು', clearAll: 'ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ',
    noHistory: 'ಇತಿಹಾಸವಿಲ್ಲ. ಮೊದಲು ವಿಷಯ ರಚಿಸಿ!',
    copy: 'ನಕಲಿಸಿ', copied: '✓ ನಕಲಿಸಲಾಗಿದೆ', download: 'ಡೌನ್‌ಲೋಡ್ .txt',
    simplePricing: 'ಸರಳ', pricingItalic: 'ಬೆಲೆ ನಿರ್ಧಾರ',
    noSurprises: 'ಯಾವುದೇ ಆಶ್ಚರ್ಯಗಳಿಲ್ಲ. ಯಾವಾಗ ಬೇಕಾದರೂ ರದ್ದು ಮಾಡಿ.',
    mostPopular: 'ಅತ್ಯಂತ ಜನಪ್ರಿಯ', getStarted: 'ಪ್ರಾರಂಭಿಸಿ', startTrial: 'ಉಚಿತ ಟ್ರಯಲ್ ಪ್ರಾರಂಭಿಸಿ', contactSales: 'ಮಾರಾಟ ಸಂಪರ್ಕಿಸಿ',
    yourProfile: 'ನಿಮ್ಮ', profileTitle: 'ಪ್ರೊಫೈಲ್',
    freePlan: 'ಉಚಿತ ಯೋಜನೆ', googleAccount: 'Google ಖಾತೆ',
    editName: '✏️ ಹೆಸರು ಸಂಪಾದಿಸಿ', currentName: 'ಪ್ರಸ್ತುತ ಹೆಸರು',
    edit: 'ಸಂಪಾದಿಸಿ', save: 'ಹೆಸರು ಉಳಿಸಿ', cancel: 'ರದ್ದು', saving: 'ಉಳಿಸುತ್ತಿದೆ...',
    emailAddress: '📧 ಇಮೇಲ್ ವಿಳಾಸ', currentEmail: 'ಪ್ರಸ್ತುತ ಇಮೇಲ್',
    change: 'ಬದಲಾಯಿಸಿ', updateEmail: 'ಇಮೇಲ್ ನವೀಕರಿಸಿ', updatingEmail: 'ಉಳಿಸುತ್ತಿದೆ...',
    newEmailLabel: 'ಹೊಸ ಇಮೇಲ್', currentPassLabel: 'ಪ್ರಸ್ತುತ ಪಾಸ್‌ವರ್ಡ್',
    passwordSecurity: '🔒 ಪಾಸ್‌ವರ್ಡ್ & ಭದ್ರತೆ',
    changePassword: '🔑 ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ', sendResetEmail: '📧 ರೀಸೆಟ್ ಇಮೇಲ್ ಕಳಿಸಿ',
    currentPass: 'ಪ್ರಸ್ತುತ ಪಾಸ್‌ವರ್ಡ್', newPass: 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ (ಕನಿಷ್ಠ 6)',
    confirmPass: 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ', updatePassword: 'ಪಾಸ್‌ವರ್ಡ್ ನವೀಕರಿಸಿ', updating: 'ನವೀಕರಿಸುತ್ತಿದೆ...',
    accountInfo: 'ℹ️ ಖಾತೆ ಮಾಹಿತಿ',
    displayName: 'ಡಿಸ್‌ಪ್ಲೇ ಹೆಸರು', email: 'ಇಮೇಲ್', userId: 'ಯೂಸರ್ ID',
    signinMethod: 'ಸೈನ್-ಇನ್ ವಿಧಾನ', accountCreated: 'ಖಾತೆ ರಚಿಸಲಾಗಿದೆ',
    dangerZone: '⚠️ ಅಪಾಯ ವಲಯ', deleteAccount: 'ಖಾತೆ ಅಳಿಸಿ',
    deleteDesc: 'ನಿಮ್ಮ ಖಾತೆ ಮತ್ತು ಎಲ್ಲಾ ಡೇಟಾವನ್ನು ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಿ.',
    delete: 'ಅಳಿಸಿ', confirmDelete: 'ಹೌದು, ನನ್ನ ಖಾತೆ ಅಳಿಸಿ',
    deleteWarning: '⚠️ ನೀವು ಖಚಿತವಾಗಿದ್ದೀರಾ? ಈ ಕ್ರಿಯೆಯನ್ನು ರದ್ದು ಮಾಡಲಾಗುವುದಿಲ್ಲ.',
    googleEmailNote: '🔗 ನಿಮ್ಮ ಖಾತೆ Google ಜೊತೆ ಲಿಂಕ್ ಆಗಿದೆ.',
    googlePassNote: '🔗 ನೀವು Google ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡಿದ್ದೀರಿ.',
    google: 'Google', emailPassword: 'ಇಮೇಲ್ & ಪಾಸ್‌ವರ್ಡ್', unknown: 'ಅಜ್ಞಾತ', notSet: 'ಹೊಂದಿಸಿಲ್ಲ',
    tooShort: 'ತುಂಬಾ ಚಿಕ್ಕದು', fair: 'ಸರಿ', good: 'ಒಳ್ಳೆಯದು', strong: 'ಬಲವಾದ',
    generateTitle: 'ರಚಿಸಿ', generateItalic: 'ಕ್ರಿಯೇಟಿವ್ ಕಂಟೆಂಟ್',
    generateDesc: 'ವಿವರಗಳನ್ನು ತುಂಬಿಸಿ ಮತ್ತು AI ಉಳಿದದ್ದು ಮಾಡಲಿ.',
    brandDetails: '✦ ಬ್ರಾಂಡ್ ವಿವರಗಳು', brandName: 'ಬ್ರಾಂಡ್ ಹೆಸರು *', industry: 'ಉದ್ಯಮ',
    targetAudience: 'ಗುರಿ ಪ್ರೇಕ್ಷಕರು', tone: 'ಟೋನ್', themeMsg: 'ಥೀಮ್ / ಮುಖ್ಯ ಸಂದೇಶ *',
    outputLang: 'ಔಟ್‌ಪುಟ್ ಭಾಷೆ', cultureProfile: '🇮🇳 ಸಾಂಸ್ಕೃತಿಕ ಪ್ರೊಫೈಲ್',
    region: 'ಪ್ರದೇಶ', festival: 'ಹಬ್ಬ / ಸಂದರ್ಭ',
    culturalElements: 'ಸಾಂಸ್ಕೃತಿಕ ಅಂಶಗಳು (2-5 ಆಯ್ಕೆ ಮಾಡಿ)', elementsSelected: 'ಅಂಶ(ಗಳು) ಆಯ್ಕೆ ಮಾಡಲಾಗಿದೆ',
    generating: 'ರಚಿಸುತ್ತಿದೆ', generatingDesc: 'ಭಾರತೀಯ ಸಾಂಸ್ಕೃತಿಕ ಸಂದರ್ಭದಲ್ಲಿ ರಚಿಸುತ್ತಿದೆ...',
    generatingTime: 'ಇದು 10-20 ಸೆಕೆಂಡ್ ತೆಗೆದುಕೊಳ್ಳಬಹುದು',
    generatedOutput: '✦ ರಚಿಸಿದ ಔಟ್‌ಪುಟ್',
    settingsTitle: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
  },
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('English')
  return (
    <LanguageContext.Provider value={{ lang, setLang, labels: APP_LABELS[lang] }}>
      {children}
    </LanguageContext.Provider>
  )
}